# Generated by Django 5.2.5 on 2025-10-28 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Назва категорii')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис категорii')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name="Ім'я клієнта")),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон клієнта')),
                ('customer_address', models.CharField(max_length=255, verbose_name='Адреса клієнта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення замовлення')),
                ('total_price', models.FloatField(verbose_name='Загальна ціна замовлення')),
                ('payment_metod', models.CharField(choices=[('cash', 'Готівка'), ('card', 'Картка при отриманні'), ('online', 'Онлайн оплата')], max_length=50, verbose_name='Спосiб оплати')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва страви')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис страви')),
                ('price', models.FloatField(verbose_name='Цiна страви')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Фото страви')),
                ('availability', models.BooleanField(default=True, verbose_name='Наявнiсть')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='main.category', verbose_name='Категорiя страви')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кiлькiсть')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dish', verbose_name='Страва')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order', verbose_name='Замовлення')),
            ],
        ),
    ]
